/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../app/src/sanity/schema.json
export type ThreeLevelsTimeline = {
  eyebrow?: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
  note?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LogoImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Kennismaken = {
  _type: "kennismaken";
  title?: string;
  text?: string;
  mailOnly?: boolean;
  background?: "default" | "paper" | "dark";
};

export type LinkBand = {
  _type: "linkBand";
  eyebrow?: string;
  title: string;
  lead?: string;
  text?: string;
  link?: Cta;
  background?: "default" | "paper" | "dark";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type LayerNav = {
  _type: "layerNav";
  eyebrow?: string;
  layers?: Array<
    {
      _key: string;
    } & PageReference
  >;
};

export type ArticleOutcome = {
  _type: "articleOutcome";
  paragraphs?: Array<string>;
  link?: Cta;
};

export type ArticleFigure = {
  _type: "articleFigure";
  diagram: "tangle" | "lens" | "dramaTriangle" | "ikInDeWij";
  caption?: string;
};

export type ArticleAside = {
  _type: "articleAside";
  title: string;
  paragraphs?: Array<string>;
  reverse?: boolean;
  quote?: string;
  image?: Photo;
  diagram?: "tangle" | "lens" | "dramaTriangle" | "ikInDeWij";
  caption?: string;
};

export type ArticleSplit = {
  _type: "articleSplit";
  title: string;
  paragraphs?: Array<string>;
};

export type FormReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "form";
};

export type ContactForm = {
  _type: "contactForm";
  detailsEyebrow?: string;
  formEyebrow?: string;
  form: FormReference;
  background?: "default" | "paper" | "dark";
};

export type PodcastEpisodes = {
  _type: "podcastEpisodes";
  eyebrow?: string;
  title: string;
  limit?: number;
  note?: string;
  background?: "default" | "paper" | "dark";
};

export type PodcastTeaser = {
  _type: "podcastTeaser";
  eyebrow?: string;
  title: string;
  lead?: string;
  link?: Cta;
  image?: Photo;
  listenTitle?: string;
  listenText?: string;
  background?: "default" | "paper" | "dark";
};

export type Logos = {
  _type: "logos";
  eyebrow?: string;
  title: string;
  lead?: string;
  rows?: Array<{
    logos?: Array<{
      image: LogoImage;
      name: string;
      url?: string;
      _type: "logo";
      _key: string;
    }>;
    _type: "logoRow";
    _key: string;
  }>;
  background?: "default" | "paper" | "dark";
};

export type CaseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "case";
};

export type Cases = {
  _type: "cases";
  layout?: "featured" | "grid";
  eyebrow?: string;
  title?: string;
  cases?: Array<
    {
      _key: string;
    } & CaseReference
  >;
  note?: string;
  background?: "default" | "paper" | "dark";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type Testimonials = {
  _type: "testimonials";
  eyebrow?: string;
  title: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  note?: string;
  background?: "default" | "paper" | "dark";
};

export type Gallery = {
  _type: "gallery";
  eyebrow?: string;
  title?: string;
  lead?: string;
  images: Array<
    {
      _key: string;
    } & Photo
  >;
  background?: "default" | "paper" | "dark";
};

export type Quote = {
  _type: "quote";
  text?: string;
  testimonial?: TestimonialReference;
  background?: "default" | "paper" | "dark";
};

export type Values = {
  _type: "values";
  variant?: "compact" | "full";
  eyebrow?: string;
  title: string;
  lead?: string;
  quote?: string;
  link?: Cta;
  itemsEyebrow?: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
  images?: Array<
    {
      _key: string;
    } & Photo
  >;
  background?: "default" | "paper" | "dark";
};

export type Stats = {
  _type: "stats";
  eyebrow?: string;
  title: string;
  items?: Array<
    {
      _key: string;
    } & Stat
  >;
  text?: string;
  link?: Cta;
  background?: "default" | "paper" | "dark";
};

export type Steps = {
  _type: "steps";
  eyebrow?: string;
  title: string;
  lead?: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
  background?: "default" | "paper" | "dark";
};

export type Timeline = {
  _type: "timeline";
  eyebrow?: string;
  title: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
  note?: string;
  plainLine?: boolean;
  background?: "default" | "paper" | "dark";
};

export type ThreeLevels = {
  _type: "threeLevels";
  eyebrow?: string;
  title: string;
  lead?: string;
  cards?: boolean;
  levels?: Array<{
    text: string;
    items?: Array<string>;
    _type: "level";
    _key: string;
  }>;
  timeline?: ThreeLevelsTimeline;
  background?: "default" | "paper" | "dark";
};

export type Kenmerken = {
  _type: "kenmerken";
  eyebrow?: string;
  title?: string;
  lead?: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
  testimonial?: TestimonialReference;
  image: Photo;
  link?: Cta;
  background?: "default" | "paper" | "dark";
};

export type CardGrid = {
  _type: "cardGrid";
  eyebrow?: string;
  title: string;
  lead?: string;
  splitHeader?: boolean;
  showBars?: boolean;
  items?: Array<{
    title: string;
    text?: string;
    link?: Cta;
    _type: "card";
    _key: string;
  }>;
  note?: string;
  link?: Cta;
  background?: "default" | "paper" | "dark";
};

export type TextSplit = {
  _type: "textSplit";
  title: string;
  lead?: string;
  paragraphs?: Array<string>;
  image?: Photo;
  background?: "default" | "paper" | "dark";
};

export type MediaText = {
  _type: "mediaText";
  eyebrow?: string;
  title: string;
  lead?: string;
  paragraphs?: Array<string>;
  images: Array<
    {
      _key: string;
    } & Photo
  >;
  imageAspect?: "3/2" | "4/5";
  narrowImage?: boolean;
  testimonial?: TestimonialReference;
  link?: Cta;
  background?: "default" | "paper" | "dark";
};

export type ArticleHero = {
  _type: "articleHero";
  layer: 1 | 2 | 3;
  title: string;
  lead: string;
  image: Photo;
  backLink?: Cta;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  title: string;
  lead: string;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
  showContactLines?: boolean;
  showPodcastLinks?: boolean;
  image?: Photo;
  imageAspect?: "16/9" | "21/9";
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & PageHero)
  | ({
      _key: string;
    } & ArticleHero)
  | ({
      _key: string;
    } & MediaText)
  | ({
      _key: string;
    } & TextSplit)
  | ({
      _key: string;
    } & CardGrid)
  | ({
      _key: string;
    } & Kenmerken)
  | ({
      _key: string;
    } & ThreeLevels)
  | ({
      _key: string;
    } & Timeline)
  | ({
      _key: string;
    } & Steps)
  | ({
      _key: string;
    } & Stats)
  | ({
      _key: string;
    } & Values)
  | ({
      _key: string;
    } & Quote)
  | ({
      _key: string;
    } & Gallery)
  | ({
      _key: string;
    } & Testimonials)
  | ({
      _key: string;
    } & Cases)
  | ({
      _key: string;
    } & Logos)
  | ({
      _key: string;
    } & PodcastTeaser)
  | ({
      _key: string;
    } & PodcastEpisodes)
  | ({
      _key: string;
    } & ContactForm)
  | ({
      _key: string;
    } & ArticleSplit)
  | ({
      _key: string;
    } & ArticleAside)
  | ({
      _key: string;
    } & ArticleFigure)
  | ({
      _key: string;
    } & ArticleOutcome)
  | ({
      _key: string;
    } & LayerNav)
  | ({
      _key: string;
    } & LinkBand)
  | ({
      _key: string;
    } & Kennismaken)
>;

export type FormField = {
  _type: "formField";
  label: string;
  name: string;
  type:
    | "text"
    | "email"
    | "tel"
    | "url"
    | "textarea"
    | "select"
    | "radio"
    | "checkbox"
    | "file"
    | "hidden";
  defaultValue?: string;
  width?: "full" | "half";
  isRequired?: boolean;
  placeholder?: string;
  helpText?: string;
  selectOptions?: Array<string>;
  radioOptions?: Array<string>;
  checkboxOptions?: Array<string>;
};

export type Stat = {
  _type: "stat";
  value: string;
  suffix?: string;
  text: string;
};

export type Item = {
  _type: "item";
  title: string;
  text?: string;
};

export type Photo = {
  _type: "photo";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Cta = {
  _type: "cta";
  label: string;
  linkType: "internal" | "external";
  internalLink?: PageReference;
  href?: string;
};

export type Link = {
  _type: "link";
  linkType: "internal" | "external";
  internalLink?: PageReference;
  href?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type FormGeneralSettings = {
  _id: string;
  _type: "formGeneralSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  adminEmail: string;
  fromEmail?: string;
  fromName?: string;
  confirmationSubject: string;
  confirmationMessage?: string;
  mailjetApiKey?: string;
  mailjetApiSecret?: string;
  mailLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  textColor?: string;
  recaptchaEnabled?: boolean;
  recaptchaSiteKey?: string;
  recaptchaSecretKey?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Form = {
  _id: string;
  _type: "form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  showTitle?: boolean;
  mode: "simple" | "steps";
  fields?: Array<
    {
      _key: string;
    } & FormField
  >;
  steps?: Array<{
    title?: string;
    fields: Array<
      {
        _key: string;
      } & FormField
    >;
    _type: "formStep";
    _key: string;
  }>;
  submitButtonText: string;
  nextButtonText?: string;
  backButtonText?: string;
  redirectAfterSubmit?: boolean;
  redirectLink?: Link;
  successTitle?: string;
  successBody?: string;
  mailRecipients?: string;
  mailSubject?: string;
  mailMessage?: string;
  sendCopyToSubmitter?: boolean;
  copySubject?: string;
  copyMessage?: string;
};

export type SiteInformation = {
  _id: string;
  _type: "siteInformation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  language?: string;
  phone?: string;
  email?: string;
  address?: Array<string>;
  addressCountry?: string;
  socialLinks?: Array<{
    platform:
      "linkedin" | "spotify" | "applePodcasts" | "instagram" | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  badges?: Array<string>;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: string;
  legalLinks?: Array<{
    label: string;
    linkType: "internal" | "external";
    internalLink?: PageReference;
    href?: string;
    _type: "navLink";
    _key: string;
  }>;
  copyright?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<{
    label: string;
    linkType: "internal" | "external";
    internalLink?: PageReference;
    href?: string;
    _type: "navLink";
    _key: string;
  }>;
};

export type PodcastEpisode = {
  _id: string;
  _type: "podcastEpisode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number?: string;
  title: string;
  description?: string;
  url?: string;
  publishedAt?: string;
};

export type Case = {
  _id: string;
  _type: "case";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  client: string;
  type?: string;
  summary?: string;
  image?: Photo;
  testimonial?: TestimonialReference;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  name: string;
  role?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  seo?: Seo;
  content?: PageBuilder;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ThreeLevelsTimeline
  | SanityImageAssetReference
  | LogoImage
  | Kennismaken
  | LinkBand
  | PageReference
  | LayerNav
  | ArticleOutcome
  | ArticleFigure
  | ArticleAside
  | ArticleSplit
  | FormReference
  | ContactForm
  | PodcastEpisodes
  | PodcastTeaser
  | Logos
  | CaseReference
  | Cases
  | TestimonialReference
  | Testimonials
  | Gallery
  | Quote
  | Values
  | Stats
  | Steps
  | Timeline
  | ThreeLevels
  | Kenmerken
  | CardGrid
  | TextSplit
  | MediaText
  | ArticleHero
  | PageHero
  | PageBuilder
  | FormField
  | Stat
  | Item
  | Photo
  | Cta
  | Link
  | Seo
  | FormGeneralSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Form
  | SiteInformation
  | Footer
  | Navigation
  | PodcastEpisode
  | Case
  | Testimonial
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../app/src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    slug,    seo,    content[]{      ...,      link{  ...,  internalLink->{    "slug": slug.current  }},      backLink{  ...,  internalLink->{    "slug": slug.current  }},      ctas[]{  ...,  internalLink->{    "slug": slug.current  }},      items[]{        ...,        link{  ...,  internalLink->{    "slug": slug.current  }}      },      testimonial->{  _id,  quote,  name,  role},      testimonials[]->{  _id,  quote,  name,  role},      cases[]->{        _id,        client,        type,        summary,        image,        testimonial->{  _id,  quote,  name,  role}      },      layers[]->{        _id,        title,        "slug": slug.current      },      _type == "podcastEpisodes" => {        "episodes": *[_type == "podcastEpisode"] | order(publishedAt desc, _createdAt asc){          _id,          number,          title,          description,          url        }      },      // The form lives in its own document so several pages can share it, and      // the public half of the reCAPTCHA settings rides along — the secret      // stays server-side, in the submit route.      _type == "contactForm" => {        form->{  _id,  title,  showTitle,  mode,  fields[],  steps[]{    title,    fields[]  },  submitButtonText,  nextButtonText,  backButtonText,  successTitle,  successBody,  redirectAfterSubmit,  redirectLink{  ...,  internalLink->{    "slug": slug.current  }}},        "recaptcha": *[_type == "formGeneralSettings"][0]{          recaptchaEnabled,          recaptchaSiteKey        }      }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  seo: Seo | null;
  content: Array<
    | {
        _key: string;
        _type: "articleAside";
        title: string;
        paragraphs?: Array<string>;
        reverse?: boolean;
        quote?: string;
        image?: Photo;
        diagram?: "dramaTriangle" | "ikInDeWij" | "lens" | "tangle";
        caption?: string;
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "articleFigure";
        diagram: "dramaTriangle" | "ikInDeWij" | "lens" | "tangle";
        caption?: string;
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "articleHero";
        layer: 1 | 2 | 3;
        title: string;
        lead: string;
        image: Photo;
        backLink: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        link: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "articleOutcome";
        paragraphs?: Array<string>;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "articleSplit";
        title: string;
        paragraphs?: Array<string>;
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "cardGrid";
        eyebrow?: string;
        title: string;
        lead?: string;
        splitHeader?: boolean;
        showBars?: boolean;
        items: Array<{
          title: string;
          text?: string;
          link: {
            _type: "cta";
            label: string;
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          } | null;
          _type: "card";
          _key: string;
        }> | null;
        note?: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "cases";
        layout?: "featured" | "grid";
        eyebrow?: string;
        title?: string;
        cases: Array<{
          _id: string;
          client: string;
          type: string | null;
          summary: string | null;
          image: Photo | null;
          testimonial: {
            _id: string;
            quote: string;
            name: string;
            role: string | null;
          } | null;
        }> | null;
        note?: string;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "contactForm";
        detailsEyebrow?: string;
        formEyebrow?: string;
        form: {
          _id: string;
          title: string;
          showTitle: boolean | null;
          mode: "simple" | "steps";
          fields: Array<
            {
              _key: string;
            } & FormField
          > | null;
          steps: Array<{
            title: string | null;
            fields: Array<
              {
                _key: string;
              } & FormField
            >;
          }> | null;
          submitButtonText: string;
          nextButtonText: string | null;
          backButtonText: string | null;
          successTitle: string | null;
          successBody: string | null;
          redirectAfterSubmit: boolean | null;
          redirectLink: {
            _type: "link";
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          } | null;
        };
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
        recaptcha: {
          recaptchaEnabled: boolean | null;
          recaptchaSiteKey: string | null;
        } | null;
      }
    | {
        _key: string;
        _type: "gallery";
        eyebrow?: string;
        title?: string;
        lead?: string;
        images: Array<
          {
            _key: string;
          } & Photo
        >;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "kenmerken";
        eyebrow?: string;
        title?: string;
        lead?: string;
        items: Array<{
          _key: string;
          _type: "item";
          title: string;
          text?: string;
          link: null;
        }> | null;
        testimonial: {
          _id: string;
          quote: string;
          name: string;
          role: string | null;
        } | null;
        image: Photo;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "kennismaken";
        title?: string;
        text?: string;
        mailOnly?: boolean;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "layerNav";
        eyebrow?: string;
        layers: Array<{
          _id: string;
          title: string;
          slug: string;
        }> | null;
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
      }
    | {
        _key: string;
        _type: "linkBand";
        eyebrow?: string;
        title: string;
        lead?: string;
        text?: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "logos";
        eyebrow?: string;
        title: string;
        lead?: string;
        rows?: Array<{
          logos?: Array<{
            image: LogoImage;
            name: string;
            url?: string;
            _type: "logo";
            _key: string;
          }>;
          _type: "logoRow";
          _key: string;
        }>;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "mediaText";
        eyebrow?: string;
        title: string;
        lead?: string;
        paragraphs?: Array<string>;
        images: Array<
          {
            _key: string;
          } & Photo
        >;
        imageAspect?: "3/2" | "4/5";
        narrowImage?: boolean;
        testimonial: {
          _id: string;
          quote: string;
          name: string;
          role: string | null;
        } | null;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        items: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "pageHero";
        eyebrow?: string;
        title: string;
        lead: string;
        ctas: Array<{
          _key: string;
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        }> | null;
        showContactLines?: boolean;
        showPodcastLinks?: boolean;
        image?: Photo;
        imageAspect?: "16/9" | "21/9";
        stats?: Array<
          {
            _key: string;
          } & Stat
        >;
        link: null;
        backLink: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "podcastEpisodes";
        eyebrow?: string;
        title: string;
        limit?: number;
        note?: string;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
        episodes: Array<{
          _id: string;
          number: string | null;
          title: string;
          description: string | null;
          url: string | null;
        }>;
      }
    | {
        _key: string;
        _type: "podcastTeaser";
        eyebrow?: string;
        title: string;
        lead?: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        image?: Photo;
        listenTitle?: string;
        listenText?: string;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "quote";
        text?: string;
        testimonial: {
          _id: string;
          quote: string;
          name: string;
          role: string | null;
        } | null;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "stats";
        eyebrow?: string;
        title: string;
        items: Array<{
          _key: string;
          _type: "stat";
          value: string;
          suffix?: string;
          text: string;
          link: null;
        }> | null;
        text?: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "steps";
        eyebrow?: string;
        title: string;
        lead?: string;
        items: Array<{
          _key: string;
          _type: "item";
          title: string;
          text?: string;
          link: null;
        }> | null;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "testimonials";
        eyebrow?: string;
        title: string;
        testimonials: Array<{
          _id: string;
          quote: string;
          name: string;
          role: string | null;
        }> | null;
        note?: string;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "textSplit";
        title: string;
        lead?: string;
        paragraphs?: Array<string>;
        image?: Photo;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "threeLevels";
        eyebrow?: string;
        title: string;
        lead?: string;
        cards?: boolean;
        levels?: Array<{
          text: string;
          items?: Array<string>;
          _type: "level";
          _key: string;
        }>;
        timeline?: ThreeLevelsTimeline;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        items: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "timeline";
        eyebrow?: string;
        title: string;
        items: Array<{
          _key: string;
          _type: "item";
          title: string;
          text?: string;
          link: null;
        }> | null;
        note?: string;
        plainLine?: boolean;
        background?: "dark" | "default" | "paper";
        link: null;
        backLink: null;
        ctas: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
    | {
        _key: string;
        _type: "values";
        variant?: "compact" | "full";
        eyebrow?: string;
        title: string;
        lead?: string;
        quote?: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        itemsEyebrow?: string;
        items: Array<{
          _key: string;
          _type: "item";
          title: string;
          text?: string;
          link: null;
        }> | null;
        images?: Array<
          {
            _key: string;
          } & Photo
        >;
        background?: "dark" | "default" | "paper";
        backLink: null;
        ctas: null;
        testimonial: null;
        testimonials: null;
        cases: null;
        layers: null;
      }
  > | null;
} | null;

// Source: ../app/src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../app/src/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{    links[]{  ...,  internalLink->{    "slug": slug.current  }}  }
export type NAVIGATION_QUERY_RESULT =
  | {
      links: null;
    }
  | {
      links: Array<{
        label: string;
        linkType: "external" | "internal";
        internalLink: {
          slug: string;
        } | null;
        href?: string;
        _type: "navLink";
        _key: string;
      }> | null;
    }
  | null;

// Source: ../app/src/sanity/queries.ts
// Variable: SITE_INFORMATION_QUERY
// Query: *[_id == "siteInformation"][0]{    name,    description,    language,    phone,    email,    address,    addressCountry,    badges,    socialLinks[]{      platform,      url    },    "logoUrl": logo.asset->url  }
export type SITE_INFORMATION_QUERY_RESULT =
  | {
      name: null;
      description: null;
      language: null;
      phone: null;
      email: null;
      address: null;
      addressCountry: null;
      badges: null;
      socialLinks: null;
      logoUrl: null;
    }
  | {
      name: string;
      description: null;
      language: null;
      phone: null;
      email: null;
      address: null;
      addressCountry: null;
      badges: null;
      socialLinks: null;
      logoUrl: null;
    }
  | {
      name: null;
      description: string | null;
      language: null;
      phone: null;
      email: null;
      address: null;
      addressCountry: null;
      badges: null;
      socialLinks: null;
      logoUrl: null;
    }
  | {
      name: string;
      description: string | null;
      language: string | null;
      phone: string | null;
      email: string | null;
      address: Array<string> | null;
      addressCountry: string | null;
      badges: Array<string> | null;
      socialLinks: Array<{
        platform:
          "applePodcasts" | "instagram" | "linkedin" | "spotify" | "youtube";
        url: string | null;
      }> | null;
      logoUrl: string | null;
    }
  | null;

// Source: ../app/src/sanity/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_id == "footer"][0]{    tagline,    legalLinks[]{  ...,  internalLink->{    "slug": slug.current  }},    copyright  }
export type FOOTER_QUERY_RESULT =
  | {
      tagline: null;
      legalLinks: null;
      copyright: null;
    }
  | {
      tagline: string | null;
      legalLinks: Array<{
        label: string;
        linkType: "external" | "internal";
        internalLink: {
          slug: string;
        } | null;
        href?: string;
        _type: "navLink";
        _key: string;
      }> | null;
      copyright: string | null;
    }
  | null;

// Source: ../app/src/sanity/queries.ts
// Variable: FORM_QUERY
// Query: *[_id == $formId && _type == "form"][0]{    _id,    title,    mailRecipients,    mailSubject,    mailMessage,    sendCopyToSubmitter,    copySubject,    copyMessage,    "fields": select(      mode == "steps" => steps[].fields[]{label, name, type, isRequired},      fields[]{label, name, type, isRequired}    )  }
export type FORM_QUERY_RESULT = {
  _id: string;
  title: string;
  mailRecipients: string | null;
  mailSubject: string | null;
  mailMessage: string | null;
  sendCopyToSubmitter: boolean | null;
  copySubject: string | null;
  copyMessage: string | null;
  fields: Array<{
    label: string;
    name: string;
    type:
      | "checkbox"
      | "email"
      | "file"
      | "hidden"
      | "radio"
      | "select"
      | "tel"
      | "text"
      | "textarea"
      | "url";
    isRequired: boolean | null;
  }> | null;
} | null;

// Source: ../app/src/sanity/queries.ts
// Variable: FORM_SETTINGS_QUERY
// Query: *[_type == "formGeneralSettings"][0]{    adminEmail,    fromEmail,    fromName,    mailLogo,    primaryColor,    textColor,    mailjetApiKey,    mailjetApiSecret,    confirmationSubject,    confirmationMessage,    recaptchaEnabled,    recaptchaSecretKey  }
export type FORM_SETTINGS_QUERY_RESULT = {
  adminEmail: string;
  fromEmail: string | null;
  fromName: string | null;
  mailLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  primaryColor: string | null;
  textColor: string | null;
  mailjetApiKey: string | null;
  mailjetApiSecret: string | null;
  confirmationSubject: string;
  confirmationMessage: string | null;
  recaptchaEnabled: boolean | null;
  recaptchaSecretKey: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    seo,\n    content[]{\n      ...,\n      link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      backLink{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      ctas[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      items[]{\n        ...,\n        link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n      },\n      testimonial->{\n  _id,\n  quote,\n  name,\n  role\n},\n      testimonials[]->{\n  _id,\n  quote,\n  name,\n  role\n},\n      cases[]->{\n        _id,\n        client,\n        type,\n        summary,\n        image,\n        testimonial->{\n  _id,\n  quote,\n  name,\n  role\n}\n      },\n      layers[]->{\n        _id,\n        title,\n        "slug": slug.current\n      },\n      _type == "podcastEpisodes" => {\n        "episodes": *[_type == "podcastEpisode"] | order(publishedAt desc, _createdAt asc){\n          _id,\n          number,\n          title,\n          description,\n          url\n        }\n      },\n      // The form lives in its own document so several pages can share it, and\n      // the public half of the reCAPTCHA settings rides along \u2014 the secret\n      // stays server-side, in the submit route.\n      _type == "contactForm" => {\n        form->{\n  _id,\n  title,\n  showTitle,\n  mode,\n  fields[],\n  steps[]{\n    title,\n    fields[]\n  },\n  submitButtonText,\n  nextButtonText,\n  backButtonText,\n  successTitle,\n  successBody,\n  redirectAfterSubmit,\n  redirectLink{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n},\n        "recaptcha": *[_type == "formGeneralSettings"][0]{\n          recaptchaEnabled,\n          recaptchaSiteKey\n        }\n      }\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_id == "navigation"][0]{\n    links[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "siteInformation"][0]{\n    name,\n    description,\n    language,\n    phone,\n    email,\n    address,\n    addressCountry,\n    badges,\n    socialLinks[]{\n      platform,\n      url\n    },\n    "logoUrl": logo.asset->url\n  }\n': SITE_INFORMATION_QUERY_RESULT;
    '\n  *[_id == "footer"][0]{\n    tagline,\n    legalLinks[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n    copyright\n  }\n': FOOTER_QUERY_RESULT;
    '\n  *[_id == $formId && _type == "form"][0]{\n    _id,\n    title,\n    mailRecipients,\n    mailSubject,\n    mailMessage,\n    sendCopyToSubmitter,\n    copySubject,\n    copyMessage,\n    "fields": select(\n      mode == "steps" => steps[].fields[]{label, name, type, isRequired},\n      fields[]{label, name, type, isRequired}\n    )\n  }\n': FORM_QUERY_RESULT;
    '\n  *[_type == "formGeneralSettings"][0]{\n    adminEmail,\n    fromEmail,\n    fromName,\n    mailLogo,\n    primaryColor,\n    textColor,\n    mailjetApiKey,\n    mailjetApiSecret,\n    confirmationSubject,\n    confirmationMessage,\n    recaptchaEnabled,\n    recaptchaSecretKey\n  }\n': FORM_SETTINGS_QUERY_RESULT;
  }
}
